services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=192.168.56.104
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=todo
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=prueba2024
    restart: always

networks:
  default:
    driver: bridge