---
- name: Configurar Tomcat con Docker en CentOS
  hosts: centos
  become: yes

  tasks:

    - name: Instalar dependencias necesarias
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Agregar repositorio oficial de Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Instalar Docker
      yum:
        name: docker-ce
        state: present

    - name: Iniciar y habilitar el servicio Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Instalar Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Crear directorio /opt/docker
      file:
        path: /opt/docker
        state: directory

    - name: Copiar docker-compose.yml al servidor
      copy:
        src: files/docker-compose.yml
        dest: /opt/docker/docker-compose.yml

    - name: Copiar Dockerfile al servidor
      copy:
        src: files/Dockerfile
        dest: /opt/docker/Dockerfile

    - name: Copiar app.properties al servidor
      copy:
        src: files/app.properties
        dest: /opt/docker/app.properties

    - name: Copiar todo.war al servidor
      copy:
        src: files/todo.war
        dest: /opt/docker/todo.war

    - name: Copiar tomcat-user.xml al servidor
      copy:
        src: files/tomcat-user.xml
        dest: /opt/docker/tomcat-user.xml

    - name: Abrir puerto 8080 en el firewall
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled

    - name: Recargar el firewall para aplicar los cambios
      ansible.builtin.command:
        cmd: firewall-cmd --reload

    - name: Construir y ejecutar contenedor Docker
      command: docker-compose -f /opt/docker/docker-compose.yml up -d