---
- name: Configurar servidor CentOS con Tomcat
  hosts: centos
  become: yes

  vars:
    tomcat_version: "8.5.73"
    tomcat_tar: "apache-tomcat-{{ tomcat_version }}.tar.gz"
    tomcat_url: "https://ftp.unicamp.br/pub/apache/tomcat/tomcat-8/v8.5.73/bin/apache-tomcat-8.5.73.tar.gz"
    app_properties_file: "/opt/tomcat/conf/app.properties"
    war_file: "/opt/tomcat/webapps/todo.war"

  tasks:
    - name: Instalar JDK de Java
      ansible.builtin.yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Descargar Tomcat
      ansible.builtin.get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/{{ tomcat_tar }}"

    - name: Extraer Tomcat
      ansible.builtin.unarchive:
        src: "/tmp/{{ tomcat_tar }}"
        dest: /opt
        remote_src: yes

    - name: Crear enlace simb贸lico para Tomcat
      ansible.builtin.file:
        src: "/opt/apache-tomcat-{{ tomcat_version }}"
        dest: /opt/tomcat
        state: link
        
    - name: Crear grupo para Tomcat
      ansible.builtin.group:
        name: tomcat
        system: yes
  
    - name: Crear usuario para Tomcat
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        create_home: no
        system: yes

    - name: Crear archivo de unidad SystemD para Tomcat
      ansible.builtin.copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
          Environment="CATALINA_HOME=/opt/tomcat"
          Environment="CATALINA_BASE=/opt/tomcat"
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Cambiar propietario del enlace simb贸lico Tomcat
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        state: link

    - name: Copiar el archivo JAR del conector JDBC a Tomcat
      copy:
        src: files/mariadb-java-client-3.1.0.jar
        dest: /opt/tomcat/lib/
        owner: tomcat
        group: tomcat
        mode: '0644'
    
    - name: Copiar el archivo context.xml a Tomcat
      ansible.builtin.copy:
        src: files/context.xml
        dest: /opt/tomcat/conf/context.xml
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Cambiar propietario del directorio de Tomcat
      ansible.builtin.file:
        path: /opt/apache-tomcat-{{ tomcat_version }}
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory

    - name: Habilitar e iniciar Tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: started
        enabled: yes

    - name: Abrir puertos de Tomcat en el firewall
      ansible.posix.firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled

    - name: Recargar el firewall para aplicar los cambios
      ansible.builtin.command:
        cmd: firewall-cmd --reload
    
    - name: Copiar archivo WAR de la aplicaci贸n ToDo
      ansible.builtin.copy:
        src: files/todo.war
        dest: "{{ war_file }}"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Crear archivo de configuraci贸n app.properties
      ansible.builtin.copy:
        content: |
          tipoDB=mysql
          jdbcURL=jdbc:mysql://192.168.56.104:3306/todo
          jdbcUsername=todo
          jdbcPassword=prueba2024
        dest: "{{ app_properties_file }}"
        owner: tomcat
        group: tomcat
        mode: '0644'
